# See https://www.chirpstack.io/application-server/install/config/ for a full
# configuration example and documentation.
[general]
log_level=4

[postgresql]
dsn="postgres://chirpstack_as:chirpstack_as@postgresql/chirpstack_as?sslmode=disable"
automigrate=true

[redis]
url="redis://redis:6379"
max_idle=10
idle_timeout="5m0s"

[application_server.codec.js]
max_execution_time="100ms"

[application_server.integration.mqtt]
server="tcp://mosquitto:1883"
qos=0
clean_session=true
client_id=""

[application_server.api]
public_host="chirpstack-application-server:8001"

[application_server.external_api]
bind="0.0.0.0:8080"
jwt_secret="verysecretxz"
disable_assign_existing_users=false

[application_server.remote_multicast_setup]
sync_interval="1s"
sync_retries=3
sync_batch_size=100

[application_server.fragmentation_session]
sync_interval="1s"
sync_retries=3
sync_batch_size=100
